import { NextRequest, NextResponse } from "next/server"
import PptxGenJS from "pptxgenjs"
import QRCode from "qrcode"
import { sessionManager } from "@/lib/session-manager"

export async function POST(req: NextRequest) {
  try {
    const {
    pptFileName,
    pptSessionId,
    flashcards = [],
    quizzes = [],
    suggestions = [],
      pptTextBySlide = [],
      pptTextCombined = "",
      baseUrl = "http://localhost:3000"
    } = await req.json()

    if (!pptFileName || !pptSessionId) {
      return NextResponse.json(
        { error: "Missing pptFileName or pptSessionId" },
        { status: 400 }
      )
    }

    // Create new presentation
    const pptx = new PptxGenJS()

    // Set presentation properties
    pptx.author = "ClassroomAI"
    pptx.company = "ClassroomAI"
    pptx.title = `${pptFileName} - Interactive Learning Materials`
    pptx.subject = "Generated Learning Materials with QR Codes"

    // Build slide list with insertions
    const slidesToAdd: Array<{ type: 'original' | 'insertion', slideNumber?: number, content?: string[], suggestion?: any }> = []

    // Add original slides
    pptTextBySlide.forEach((slideContent: string[], index: number) => {
      slidesToAdd.push({
        type: 'original',
        slideNumber: index + 1,
        content: slideContent
      })
    })

    // Add insertion slides
    suggestions.forEach((suggestion: any) => {
      const positionOffset = suggestion.position === 'before' ? 0.1 : suggestion.position === 'during' ? 0.2 : 0.3
      slidesToAdd.push({
        type: 'insertion',
        slideNumber: suggestion.slide + positionOffset,
        suggestion
      })
    })

    // Sort slides by slideNumber
    slidesToAdd.sort((a, b) => (a.slideNumber || 0) - (b.slideNumber || 0))

    // Generate QR codes if needed
    const hasFlashcardSuggestions = suggestions.some((s: any) => s.type === 'flashcard')
    const hasQuizSuggestions = suggestions.some((s: any) => s.type === 'quiz')

    let flashcardQRCode: string | null = null
    let quizQRCode: string | null = null
    let flashcardUrl: string | null = null
    let quizUrl: string | null = null

    if (hasFlashcardSuggestions && flashcards.length > 0) {
      const flashcardSessionId = `flashcards_${pptSessionId}_${Date.now()}`
      flashcardUrl = `${baseUrl}/student/${flashcardSessionId}/flashcards`
      flashcardQRCode = await QRCode.toDataURL(flashcardUrl, {
        width: 300,
        margin: 2,
        color: { dark: '#000000', light: '#FFFFFF' }
      })
      // Create session
      sessionManager.createSession(flashcardSessionId, "flashcards", flashcards, pptFileName, pptSessionId)
    }

    if (hasQuizSuggestions && quizzes.length > 0) {
      const quizSessionId = `quiz_${pptSessionId}_${Date.now()}`
      quizUrl = `${baseUrl}/student/${quizSessionId}/quiz`
      quizQRCode = await QRCode.toDataURL(quizUrl, {
        width: 300,
        margin: 2,
        color: { dark: '#000000', light: '#FFFFFF' }
      })
      // Create session
      sessionManager.createSession(quizSessionId, "quiz", quizzes, pptFileName, pptSessionId)
    }

    // Title slide
    const titleSlide = pptx.addSlide()
    titleSlide.addText(`${pptFileName}`, {
    x: 1,
    y: 1,
    w: 8,
    h: 1.5,
    fontSize: 36,
    bold: true,
    color: "363636",
    align: "center"
    })
    titleSlide.addText("Interactive Learning Materials", {
    x: 1,
    y: 2.5,
    w: 8,
    h: 1,
    fontSize: 24,
    color: "666666",
    align: "center"
    })
    titleSlide.addText("Generated by ClassroomAI", {
    x: 1,
    y: 3.5,
    w: 8,
    h: 1,
    fontSize: 18,
    color: "999999",
    align: "center"
    })

    // Add slides in order
    for (const slideInfo of slidesToAdd) {
      if (slideInfo.type === 'original') {
        const slide = pptx.addSlide()
        // Add text content
        const content = slideInfo.content?.join('\n') || ''
        if (content) {
          slide.addText(content, {
            x: 0.5,
            y: 0.5,
            w: 9,
            h: 5,
            fontSize: 18,
            color: "363636"
          })
        }
      } else if (slideInfo.type === 'insertion') {
        const suggestion = slideInfo.suggestion
        if (suggestion.type === 'flashcard' && flashcardQRCode && flashcardUrl) {
          const slide = pptx.addSlide()
          slide.addText("📚 Flashcards", {
            x: 1,
            y: 0.5,
            w: 8,
            h: 1,
            fontSize: 28,
            bold: true,
            color: "363636"
          })
          // Add QR code
          const qrBuffer = Buffer.from(flashcardQRCode.split(',')[1], 'base64')
          slide.addImage({
            data: qrBuffer,
            x: 1,
            y: 1.5,
            w: 2,
            h: 2
          })
          slide.addText("Scan this QR code to access flashcards", {
            x: 3.5,
            y: 1.5,
            w: 5,
            h: 0.5,
            fontSize: 16,
            bold: true,
            color: "363636"
          })
          slide.addText(`Total Cards: ${flashcards.length}`, {
            x: 3.5,
            y: 2,
            w: 5,
            h: 0.5,
            fontSize: 14,
            color: "666666"
          })
          slide.addText("Backup Link:", {
            x: 3.5,
            y: 2.5,
            w: 5,
            h: 0.5,
            fontSize: 14,
            bold: true,
            color: "363636"
          })
          slide.addText(flashcardUrl, {
            x: 3.5,
            y: 3,
            w: 5,
            h: 1,
            fontSize: 10,
            color: "0066CC",
            breakLine: true
          })
          // Add reason
          slide.addText(`Reason: ${suggestion.reason}`, {
            x: 1,
            y: 4.5,
            w: 8,
            h: 0.5,
            fontSize: 14,
            color: "666666"
          })
        } else if (suggestion.type === 'quiz' && quizQRCode && quizUrl) {
          const slide = pptx.addSlide()
          slide.addText("🧠 Quiz", {
            x: 1,
            y: 0.5,
            w: 8,
            h: 1,
            fontSize: 28,
            bold: true,
            color: "363636"
          })
          // Add QR code
          const qrBuffer = Buffer.from(quizQRCode.split(',')[1], 'base64')
          slide.addImage({
            data: qrBuffer,
            x: 1,
            y: 1.5,
            w: 2,
            h: 2
          })
          slide.addText("Scan this QR code to access quiz", {
            x: 3.5,
            y: 1.5,
            w: 5,
            h: 0.5,
            fontSize: 16,
            bold: true,
            color: "363636"
          })
          slide.addText(`Total Questions: ${quizzes.length}`, {
            x: 3.5,
            y: 2,
            w: 5,
            h: 0.5,
            fontSize: 14,
            color: "666666"
          })
          slide.addText("Backup Link:", {
            x: 3.5,
            y: 2.5,
            w: 5,
            h: 0.5,
            fontSize: 14,
            bold: true,
            color: "363636"
          })
          slide.addText(quizUrl, {
            x: 3.5,
            y: 3,
            w: 5,
            h: 1,
            fontSize: 10,
            color: "0066CC",
            breakLine: true
          })
          // Add reason
          slide.addText(`Reason: ${suggestion.reason}`, {
            x: 1,
            y: 4.5,
            w: 8,
            h: 0.5,
            fontSize: 14,
            color: "666666"
          })
        }
      }
    }

    // Generate QR codes and URLs for flashcards (legacy - if no suggestions but have content)
    if (!hasFlashcardSuggestions && flashcards.length > 0) {
      const flashcardSessionId = `flashcards_${pptSessionId}_${Date.now()}`
      const flashcardUrl = `${baseUrl}/student/${flashcardSessionId}/flashcards`
      sessionManager.createSession(flashcardSessionId, "flashcards", flashcards, pptFileName, pptSessionId)
      
      // Generate QR code for flashcards
      const flashcardQRCode = await QRCode.toDataURL(flashcardUrl, {
        width: 300,
        margin: 2,
        color: { dark: '#000000', light: '#FFFFFF' }
      })

      // Flashcards slide
      const flashcardSlide = pptx.addSlide()
      flashcardSlide.addText("📚 Flashcards", {
        x: 1,
        y: 0.5,
        w: 8,
        h: 1,
        fontSize: 28,
        bold: true,
        color: "363636"
      })
      
      // Add QR code (we'll need to convert data URL to buffer)
      const qrBuffer = Buffer.from(flashcardQRCode.split(',')[1], 'base64')
      flashcardSlide.addImage({
        data: qrBuffer,
        x: 1,
        y: 1.5,
        w: 2,
        h: 2
      })
      
      flashcardSlide.addText("Scan this QR code to access flashcards", {
        x: 3.5,
        y: 1.5,
        w: 5,
        h: 0.5,
        fontSize: 16,
        bold: true,
        color: "363636"
      })
      
      flashcardSlide.addText(`Total Cards: ${flashcards.length}`, {
        x: 3.5,
        y: 2,
        w: 5,
        h: 0.5,
        fontSize: 14,
        color: "666666"
      })
      
      flashcardSlide.addText("Backup Link:", {
        x: 3.5,
        y: 2.5,
        w: 5,
        h: 0.5,
        fontSize: 14,
        bold: true,
        color: "363636"
      })
      
      flashcardSlide.addText(flashcardUrl, {
        x: 3.5,
        y: 3,
        w: 5,
        h: 1,
        fontSize: 10,
        color: "0066CC",
        breakLine: true
      })

      // Sample flashcards preview
      if (flashcards.length > 0) {
        flashcardSlide.addText("Sample Cards:", {
          x: 1,
          y: 4.5,
          w: 8,
          h: 0.5,
          fontSize: 16,
          bold: true,
          color: "363636"
        })
        
        const sampleCards = flashcards.slice(0, 3)
        sampleCards.forEach((card: any, index: number) => {
          const yPos = 5 + (index * 0.8)
          flashcardSlide.addText(`Q${index + 1}: ${card.question}`, {
            x: 1,
            y: yPos,
            w: 8,
            h: 0.4,
            fontSize: 12,
            color: "363636"
          })
        })
      }
    }

    // Generate QR codes and URLs for quizzes
    if (quizzes.length > 0) {
      const quizSessionId = `quiz_${pptSessionId}_${Date.now()}`
      const quizUrl = `${baseUrl}/student/${quizSessionId}/quiz`
      sessionManager.createSession(quizSessionId, "quiz", quizzes, pptFileName, pptSessionId)
      
      // Generate QR code for quiz
      const quizQRCode = await QRCode.toDataURL(quizUrl, {
        width: 300,
        margin: 2,
        color: { dark: '#000000', light: '#FFFFFF' }
      })

      // Quiz slide
      const quizSlide = pptx.addSlide()
      quizSlide.addText("🧠 Quiz", {
        x: 1,
        y: 0.5,
        w: 8,
        h: 1,
        fontSize: 28,
        bold: true,
        color: "363636"
      })
      
      // Add QR code
      const quizQrBuffer = Buffer.from(quizQRCode.split(',')[1], 'base64')
      quizSlide.addImage({
        data: quizQrBuffer,
        x: 1,
        y: 1.5,
        w: 2,
        h: 2
      })
      
      quizSlide.addText("Scan this QR code to access quiz", {
        x: 3.5,
        y: 1.5,
        w: 5,
        h: 0.5,
        fontSize: 16,
        bold: true,
        color: "363636"
      })
      
      quizSlide.addText(`Total Questions: ${quizzes.length}`, {
        x: 3.5,
        y: 2,
        w: 5,
        h: 0.5,
        fontSize: 14,
        color: "666666"
      })
      
      quizSlide.addText("Backup Link:", {
        x: 3.5,
        y: 2.5,
        w: 5,
        h: 0.5,
        fontSize: 14,
        bold: true,
        color: "363636"
      })
      
      quizSlide.addText(quizUrl, {
        x: 3.5,
        y: 3,
        w: 5,
        h: 1,
        fontSize: 10,
        color: "0066CC",
        breakLine: true
      })

      // Sample quiz questions preview
      if (quizzes.length > 0) {
        quizSlide.addText("Sample Questions:", {
          x: 1,
          y: 4.5,
          w: 8,
          h: 0.5,
          fontSize: 16,
          bold: true,
          color: "363636"
        })
        
        const sampleQuestions = quizzes.slice(0, 2)
        sampleQuestions.forEach((quiz: any, index: number) => {
          const yPos = 5 + (index * 1.2)
          quizSlide.addText(`Q${index + 1}: ${quiz.question}`, {
            x: 1,
            y: yPos,
            w: 8,
            h: 0.4,
            fontSize: 12,
            color: "363636"
          })
          quizSlide.addText(`Options: ${quiz.options.join(", ")}`, {
            x: 1,
            y: yPos + 0.4,
            w: 8,
            h: 0.4,
            fontSize: 10,
            color: "666666"
          })
        })
      }
    }

    // Instructions slide
    const instructionsSlide = pptx.addSlide()
    instructionsSlide.addText("📱 How to Use", {
      x: 1,
      y: 0.5,
      w: 8,
      h: 1,
      fontSize: 28,
      bold: true,
      color: "363636"
    })
    
    instructionsSlide.addText("1. Students scan QR codes with their phone camera", {
      x: 1,
      y: 1.5,
      w: 8,
      h: 0.5,
      fontSize: 16,
      color: "363636"
    })
    
    instructionsSlide.addText("2. They will be redirected to interactive learning materials", {
      x: 1,
      y: 2,
      w: 8,
      h: 0.5,
      fontSize: 16,
      color: "363636"
    })
    
    instructionsSlide.addText("3. Students can practice flashcards or take quizzes", {
      x: 1,
      y: 2.5,
      w: 8,
      h: 0.5,
      fontSize: 16,
      color: "363636"
    })
    
    instructionsSlide.addText("4. Real-time feedback and scoring is provided", {
      x: 1,
      y: 3,
      w: 8,
      h: 0.5,
      fontSize: 16,
      color: "363636"
    })
    
    instructionsSlide.addText("💡 Tip: Backup links are provided in case QR codes don't work", {
      x: 1,
      y: 4,
      w: 8,
      h: 0.5,
      fontSize: 14,
      color: "666666",
      italic: true
    })

    // Generate the presentation
    const buffer = await pptx.writeFile({ outputType: "nodebuffer" })
    
    // Return the file
    return new NextResponse(buffer, {
      headers: {
        "Content-Type": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "Content-Disposition": `attachment; filename="${pptFileName}_interactive.pptx"`
      }
    })

  } catch (error: any) {
    console.error("PPTX generation error:", error)
    return NextResponse.json(
      { error: error.message || "Failed to generate PPTX" },
      { status: 500 }
    )
  }
}


